### PR TITLE
sdm632-common: Kick unneeded problematic FM blobs

### PR DESCRIPTION
**Pull request by wh0dat**
* fixes FM station freeze / power cycle issues

Signed-off-by: wh0dat <whodat@remainsilent.net>
Change-Id: Ic834a99e14d4e3d6b42a910ae630769de5d11e26

### CODE REVIEW

**Comment by javelinanddart** [comment]
Both of these need to be script generated. Neither of them are.

**Comment by npjohnson** [comment]
Submit this to gerrit first.

**Comment by npjohnson** [comment]
by that, I mean the prop files txt change

**Comment by erfanoabdi** [comment]
already there, https://review.lineageos.org/c/LineageOS/android_device_motorola_sdm632-common/+/272030
need testings, i'm waiting for 1 official build rolls and after that  will merge this, don't want to users go back to very old build if anything goes wrong

**Pull request closed without merging**
