### PR TITLE
Gingerbread

### PR DESCRIPTION
**Pull request by JBirdVegas**
accidentally pulled in some of my droid2 ICS work. This fixes

### CODE REVIEW

**Comment by epsylon3** [comment]
could you rebase your branch on koush one to reduce commit list

**Comment by JBirdVegas** [comment]
Not a problem... I rebased and squashed

**Comment by epsylon3** [comment]
oh didnt mean squashed :p but you need to fetch koush repo before the rebase, else i need to revert the last two commits

git branch gingerbread
git remote add koush git://.....
git fetch koush
git rebase koush/gingerbread gingerbread

**Comment by JBirdVegas** [comment]
rebase failed. I just opened a new pull request here https://github.com/koush/proprietary_vendor_motorola/pull/25 sorry for the confusion.

**Pull request closed without merging**
