### PR TITLE
making sure charge_only_mode gets added into the recovery.img

### PR DESCRIPTION
**Pull request by jr0dd**

### CODE REVIEW

**Comment by turl** [comment]
Why do you want it on there?

**Comment by jr0dd** [comment]
@Turl because some people are a pain in the ass and really want to charge their phone in the recovery. Really it was mentioned to me about the Morrison by adlx. Just made the changes to the motus so far.

**Comment by turl** [comment]
But wouldn't it prevent you from using recovery plugged in?

**Comment by jr0dd** [comment]
Nope. It works just fine. The stock moto recovery.img's for the BF/Cliq/XT all had that binary included. so did those Amon_RA based recoveries I created for those devices as well. Again I couldn't care less about it but to some it's important lol.

**Comment by turl** [comment]
But that binary shows the big battery icon when charging. That's all it does. And if you run it on recovery, you wouldn't be able to use it when plugged because the giant drawing would be there. Including it but not launching it on init is pointless, just using up valuable recovery space :p

This reminded me we need to ship setrecovery on there

**Comment by jr0dd** [comment]
Hmm. Maybe I should look into this more.

**Pull request merged**
