### PR TITLE
peregrine: msm8226-common: bring in 5.1 blobs

### PR DESCRIPTION
**Pull request by rabih**
Hold off on this until other devices recieve the 5.1 ota.

### CODE REVIEW

**Comment by rabih** [comment]
Can MotGeoFenceSvc be removed as it isn't applicable anymore?

**Comment by somcom3x** [comment]
Internal speaker is currently broken, there's a qc-qmi spam http://pastebin.com/rx6PEfzr related to TX. Currently investigating it.

**Comment by Wechy77** [comment]
The msm8226-common apks and framework files are not deodexed.

**Comment by h2o64** [comment]
@somcom3x Yes, this apk can be removed. However we need to make sure that overlay get it too https://github.com/h2o64/android_device_motorola_falcon/commit/56e6092add6ba1fa32914235c391da034c307710
Also is "  
- Fixes torch intensity brightness on peregrine.
- Fixes issue with low display brightness causing a flashing display.
  " 
  thanks to updating blobs are did you just add a specific library ?

**Comment by h2o64** [comment]
EDIT : I also made that https://github.com/h2o64/proprietary_vendor_motorola/commit/b022ce4ed7f59c5d901a30d0e853ed58ab7a8199
I made it for the LPB23.13-37 35 when it has been released and now I updated it. Everything works on falcon and titan (need to be verified). Of course, the camera revert here https://github.com/CyanogenMod/android_kernel_motorola_msm8226/commit/afc28fcbc11d7ff1876827699e622fb2b0f82f32 must be reverted again.

**Comment by luca020400** [comment]
https://github.com/luca020400/proprietary_vendor_motorola/commits/cm-12.1
1) Add deodexed apk/jar ( included in msm8226-common: update proprietary files  )
2) Remove MotGeoFenceSvc
3) Update thea/titan/falcon blobs
4) Commonize the libmm*
And the other commits in this pull request
Needs http://review.cyanogenmod.org/#/q/topic:%22blobs+5.1%22 & http://review.cyanogenmod.org/#/c/104072/

Tested and working fine on titan/thea

**Comment by Alberto97** [comment]
@somcom3x I think you shouldn't update charge_only_mode binary. The current one is the only wich works properly (it allows booting the phone from the offline charging mode in the correct way). Current Adreno libraries  are taken from bacon and probably newer than these ones. Finally you should check widevine feature too; current libraries are from hammerhead since moto ones seem broken

EDIT: I forgot, TimeService is already from GPE 5.1

**Comment by luca020400** [comment]
I tested widevine and it's working properly
I didn't update charge_only_mode in my repo

**Comment by rabih** [comment]
@Wechy77 I'll get this done soon, just saw your reply.
@h2o64 Just saw your reply. The torch is modified by the updates to the camera and sensors.msm8226.so. Also, http://review.cyanogenmod.org/#/c/104072/
@Alberto97 Widevine is working fine, along with charge_only_mode. If we're sticking to the otter's I'll remove it.

**Comment by rabih** [comment]
Updated pull request to @luca020400's branch.

**Comment by Wechy77** [comment]
@somcom3x @luca020400 can we revert back to old time_daemon too? 
See my comment at the end of this change: https://github.com/TheMuppets/proprietary_vendor_motorola/commit/6622ea3456a344d0c2c26a3aa588505e0c463bff
I have the "time traveller bug" and the old bin fixes it.

**Comment by luca020400** [comment]
@Wechy77 I had  the "time traveller" bug on old blobs
After 5.0.2 blobs merge is gone

**Comment by rabih** [comment]
See #181 for updated changes

**Pull request closed without merging**
