### PR TITLE
msm8226: Update proprietary files

### PR DESCRIPTION
**Pull request by Alberto97**

### CODE REVIEW

**Comment by luca020400** [comment]
You may update msm8226-common too

**Comment by Alberto97** [comment]
I know, but I need a titan/thea tester to check for potential problems

**Comment by luca020400** [comment]
Upload new vendor and I'll test it on thea/titan

**Comment by Alberto97** [comment]
New blobs for msm8226-common, titan and thea uploaded

**Comment by stucki** [comment]
How about picking the proprietary files from peregrine? That is the most recent version afaik.

**Comment by Alberto97** [comment]
I'm not able to deodex 5.1 apk/jar files

**Comment by Wechy77** [comment]
@Alberto97 I used this tool to deoxed (apk and jar): http://forum.xda-developers.com/android/software-hacking/script-app-joeldroid-lollipop-batch-t2980857

**Comment by Alberto97** [comment]
Already tried; after selecting system folder and starting the process it says it can't find framework folder and Boot.oat or something similar. Anyway I deodexed 5.0 files by following this guide http://forum.xda-developers.com/android/software-hacking/guide-android-l-5-0-lollipop-deodex-t2967242, which that tool is based on, but it doesn't work with 5.1 files

**Comment by Alberto97** [comment]
Anyway since thea, titan and falcon didn't get 5.1 I think there is a better compatibility between 5.0.2 msm8226-common and 5.0.2 device specific blobs than 5.1 msm8226-common and 5.0.2 device specific blobs

**Comment by luca020400** [comment]
Alberto remove titan & thea blobs update
In this way we're going to have non working camera
Anyway current blobs are up to date

**Comment by Alberto97** [comment]
But LuK tested them with msm8226-common files and he said camera is working...

**Comment by luca020400** [comment]
Oh sorry ( holidays )

Il giorno mer 8 lug 2015 20:55 Alberto Pedron notifications@github.com ha
scritto:

**Comment by Alberto97** [comment]
Updated to allow #171 merge

**Pull request merged**
