### PR TITLE
prop files to fix Camera/Camcorder and Video playback

### PR DESCRIPTION
**Pull request by RevNumbers**
the DX folks have been flashing a zip with these fixes after installing the official builds... they've asked me to add them to the official builds... I did a test build and everyone said it's working great.  There are 2 other things that I'll do through gerrit.

### CODE REVIEW

**Comment by koush** [comment]
@cvpcs please take a look

**Comment by RevNumbers** [comment]
Hummm... good point on the Vendor_ti_omx stuff I'll remove those

I agree on libstagefright... it's not good to keep it in prop, let me see what i can do about it

**Comment by cvpcs** [comment]
i have been attempting to get libLCML and libbridge to work in source for awhile now and haven't been successful, so it may be a good idea to just include those as props for awhile now in the interim.  i had not anticipated it being as difficult as it has been to get them building properly.

i do agree, however, with Quarx2k that we should try and get it working with a source-built libstagefright, as there are many CM changes to stagefright and using a prop libstagefright would likely result in a ridiculous amount of ABI breaks in the future.

**Comment by RevNumbers** [comment]
agreed... I'll see what exactly breaks with the generic libstagefright and go from there

**Comment by RevNumbers** [comment]
for now, i'm going to close this pull request, and abandon the gerrit commit... I'm working on stagefright but it's being stubborn, thanks for the comments/advice/suggestions/ideas :)

**Pull request closed without merging**
