### PR TITLE
Add Moto E 2015 LTE (surnia)

### PR DESCRIPTION
**Pull request by ramsudharsan**

### CODE REVIEW

**Comment by ramsudharsan** [comment]
@luk1337 Do I have to amend the commit and resend the pull request?

**Comment by luk1337** [comment]
You don't have to open a new pull request. git push -f will update the
current one.

**Comment by ramsudharsan** [comment]
@luk1337 Ok will do that now! But do check this once:
screenshot from 2015-10-04 16 14 57

**Comment by akhilnarang** [comment]
@ramsudharsan this ain't the Linux kernel tree :3

**Comment by luk1337** [comment]
It does not matter in this case.

**Comment by ramsudharsan** [comment]
I think its solved!

**Pull request closed without merging**
