### PR TITLE
Update blobs from Harpia NPIS26.48-43-2

### PR DESCRIPTION
**Pull request by SubhrajyotiSen**
The new blobs additionally fix VoLTE without needing to update blobs from OnePlus3

### CODE REVIEW

**Comment by SubhrajyotiSen** [comment]
@sultanqasim Can you please take a look at this when you are free?

**Comment by npjohnson** [comment]
At minimum, you can't strip copyright from CyanogenMod on the hardpia/ directory.

**Comment by SubhrajyotiSen** [comment]
Thanks for pointing it out. I have restored the CyanogenMod copyright

**Comment by npjohnson** [comment]
Please forcepush over your branch with the keeping of the copyrights ammended to the actual commit instead of fixing it a commit later.

**Comment by SubhrajyotiSen** [comment]
Done

**Comment by sultanqasim** [comment]
Sorry for the very late review. I'd be happy to merge this (and appreciative) if you update this commit to NPIS26.48-43-2 (June 2018). I have no way to test VoLTE and no idea why these changes would fix/not fix VoLTE. If you can get VoLTE working by just updating Motorola blobs from the stock ROM, I'd be super grateful. Please test VoLTE with the blob set you'll provide (with no additional APKs or external blobs added). Once again, many thanks for your help.

Also, please use setup-makefiles.sh to update makefiles. It will ensure things like "Copyright (C) 2017-2018 The LineageOS Project" and make sure no mistakes are made.

**Comment by SubhrajyotiSen** [comment]
I will pull the blobs from the June review and update this PR

**Comment by sultanqasim** [comment]
Many thanks!

**Comment by SubhrajyotiSen** [comment]
I have updated the PR with the latest blobs

**Comment by sultanqasim** [comment]
Looks good to me on first review. I’ll do some testing on surnia/harpia/lux this week. Do these blob changes also fix VoLTE?

**Comment by SubhrajyotiSen** [comment]
Surprisingly, yes. Even I could not understand how. You can send me a test build to confirm working VoLTE once you make one

**Comment by sultanqasim** [comment]
Will do next week.

**Comment by sultanqasim** [comment]
Looking at this commit again, the most significant change is updating netmgr blobs (unpinning them from addison). https://review.lineageos.org/#/c/LineageOS/android_device_motorola_msm8916-common/+/224209/

**Comment by sultanqasim** [comment]
Here's a build you can try: http://www.mediafire.com/file/l74uc91nact18n1/lineage-14.1-20180814-UNOFFICIAL-harpia.zip/file

Let me know if VoLTE works.

**Comment by SubhrajyotiSen** [comment]
VoLTE is working properly now. I made a call and the audio was working correctly on both sides.

**Pull request merged**
