### PR TITLE
Droid2: this is the updated proprietary files needed to move to the GB k...

### PR DESCRIPTION
**Pull request by JBirdVegas**
...ernel

I'm about to submit to the device part to gerrit but I wanted to ref
this pull request

### CODE REVIEW

**Comment by JBirdVegas** [comment]
The relevant gerrit commit is located @ http://review.cyanogenmod.com/#change,11490 and is a fork of github.com/CM7-GB

**Comment by tpruvot** [comment]
its a delete only commit right ?

**Comment by JBirdVegas** [comment]
@tpruvot yea that was a derp and is fixed with https://github.com/JBirdVegas/proprietary_vendor_motorola/commit/0705390dd7410ab4515c1804c0742e7b459c0055

**Comment by tpruvot** [comment]
i pushed a squashed commit of 2 first ones so it doesnt affect log of droid2we

**Comment by JBirdVegas** [comment]
Thanks

**Pull request closed without merging**
