### PR TITLE
Condor : Update blobs for 5.1

### PR DESCRIPTION
**Pull request by ashwinr64**
- Motorola version: LPC23.13-34.2

### CODE REVIEW

**Comment by parheliamm** [comment]
Qucik questions: I saw you update APKs, where did you get the apks with dex file?

**Comment by percy-g2** [comment]
have you tested these blobs  ?

**Comment by ashwinr64** [comment]
Yup.so far so good.for ur satisfaction u may pick this.and pick everything from the topic
http://review.cyanogenmod.org/#/q/topic:5.1-condor-blobs

**Comment by percy-g2** [comment]
okay once this is merged , i will verify those in cm gerrit.

**Comment by ashwinr64** [comment]
Great!!

**Comment by percy-g2** [comment]
@intervigilium merge this

**Comment by ashwinr64** [comment]
We need to merge those kernel commits as well for the camera to work

**Comment by intervigilium** [comment]
BTW, in the future, instead of cherry-picking all the commits from an upstream tag, you can also just merge the upstream tag and push to gerrit, or have someone push it to gerrit for you.

**Comment by percy-g2** [comment]
Yes that will be better

**Pull request merged**
