### PR TITLE
msm8226-common: Update widevine libs

### PR DESCRIPTION
**Pull request by luk1337**
- Package version: hammerhead-LMY47I

Change-Id: I947ef6f01ff3b1f92118b30cf7b03c235ffe5725

### CODE REVIEW

**Comment by intervigilium** [comment]
What does 568c87c correspond to? The latest is lmy-48b AFAIK.

**Comment by luk1337** [comment]
568c87c = TheMuppets branch.
https://github.com/TheMuppets/proprietary_vendor_lge/commits/568c87c

**Comment by intervigilium** [comment]
Use the nexus package ID instead.

**Comment by luk1337** [comment]
ok, done.

**Pull request merged**
