### PR TITLE
Proximity Sensor Fix for 5.1

### PR DESCRIPTION
**Pull request by pjgraber03**
Thanks to mikeyxda for his fix. This fixes the proximity problem in 5.1.  The issue is its to sensitive and phone calls and waking the device are hard due the the sensitivity of the sensor this fixes that issue.  It allows the phone to wake when checking the proximity sensor and allows the screen to turn on and off correctly while in a phone call.

### CODE REVIEW

**Comment by dhacker29** [comment]
Where are these files from?

**Comment by ghost** [comment]
http://forum.xda-developers.com/nexus-6/development/mod-fix-proximity-sensor-5-1-rom-t3069031

You can find more info here

**Comment by dhacker29** [comment]
That gives no information on the source of these files (what release they were pulled from or if they were edited).

**Comment by pjgraber03** [comment]
They were pulled from the last (most recent) 5.0.1 build: LRX22C.

**Comment by pjgraber03** [comment]
Can these be added please

**Pull request closed without merging**
