### PR TITLE
odessa: fix ultra wide camera for odessa

### PR DESCRIPTION
**Pull request by Theimposter65**

### CODE REVIEW

**Comment by erfanoabdi** [comment]
where is this blob coming from?

**Comment by wiktorek140** [comment]
I might coming from stock. I have it there but because its locked, i cannot compare it

**Comment by erfanoabdi** [comment]
so please update device tree from gerrit as well, also update other blobs if needed as well
i'll review and merge

**Comment by Theimposter65** [comment]
This blob is from stock RPAS31.Q2-59-17-4-5-5 same as other vendor blobs and about device tree i see that Odessa needs some more changes related to NFC(I've already fixed it), I'll be pushing soon to gerrit.

**Pull request closed without merging**
