### PR TITLE
titan: Add titan proprietary files

### PR DESCRIPTION
**Pull request by luk1337**
- We can't use camera libs from msm8226-common so I moved them to falcon & peregrine

### CODE REVIEW

**Comment by intervigilium** [comment]
Break up the camera lib movement and titan import into separate commits.

**Comment by luk1337** [comment]
done

**Comment by intervigilium** [comment]
Oops, didn't realize your setup-makefiles.sh patches had the libs ordered incorrectly.

**Comment by luk1337** [comment]
It's ok now.

**Comment by intervigilium** [comment]
I merged the camera lib movement separately.

**Comment by luk1337** [comment]
So should I remove cam commit from my repo, cuz there is merge conflict.

**Comment by intervigilium** [comment]
Might as well squash these two down

**Comment by luk1337** [comment]
Done.

**Pull request merged**
