### PR TITLE
griffin: update vendor blobs

### PR DESCRIPTION
**Pull request by Shr3ps**
griffin: switch to prebuilt audio HAL
griffin: remove Moto Voice
griffin: fix aptX
griffin: switch to shared graphics driver repository
griffin: fix Moto/Motorola Camera
griffin: update ModFmwkProxyService

### CODE REVIEW

**Comment by invisiblek** [comment]
prebuilt audio hal?

**Comment by luca020400** [comment]
Fix your ACDB ids
I know moto uses arizona chips, but they should work with qcom audio hal without any problem

**Comment by Shr3ps** [comment]
Using the audio prebuild HAL fixes too major bugs without fix founded for now:
- Fix in-call microphone when using Speakers
- Use the Moto specifics to make Moto Mods (Audio JBL) compatible

**Comment by ashwinr64** [comment]
Why don't you amend it , Shreps ?

**Comment by Shr3ps** [comment]
Squash done

**Pull request merged**
