### PR TITLE
sdm660-common: Add QCOM WFD Blobs

### PR DESCRIPTION
**Pull request by daedroza**
Pull all the necessary blobs.
Based on **OnePlus 3** Binaries

### CODE REVIEW

**Comment by daedroza** [comment]
@erfanoabdi : Please keep this on hold until the topic is merged.

**Comment by npjohnson** [comment]
Guessing from your fp of the revert that you won't be including this?

Feel free to reopen.

**Comment by daedroza** [comment]
@npjohnson : Could you please re-open? I don't see any PR reopen button.

**Comment by npjohnson** [comment]
branch was forcepushed between now and then, will need a new PR

**Pull request closed without merging**
